go vet ./functions/ingredient/get
go vet ./functions/ingredient/put
go vet ./functions/recipe/get
go vet ./functions/recipe/p_id/delete
go vet ./functions/recipe/p_id/get
go vet ./functions/recipe/post
go vet ./functions/recipe/put
go vet ./functions/recipe/search/get
go vet ./functions/userview/get
go vet ./functions/userview/p_id/get

go test ./functions/ingredient/get
go test ./functions/ingredient/put
go test ./functions/recipe/get
go test ./functions/recipe/p_id/delete
go test ./functions/recipe/p_id/get
go test ./functions/recipe/post
go test ./functions/recipe/put
go test ./functions/recipe/search/get
go test ./functions/userview/get
go test ./functions/userview/p_id/get