go vet ./functions/clipping/p_id/delete
go vet ./functions/clipping/p_id/get
go vet ./functions/clipping/post
go vet ./functions/clipping/put
go vet ./functions/clipping/search/get
go vet ./functions/image/get
go vet ./functions/ingredient/get
go vet ./functions/ingredient/put
go vet ./functions/public/image/get
go vet ./functions/public/recipe/get
go vet ./functions/recipe/get
go vet ./functions/recipe/p_id/delete
go vet ./functions/recipe/p_id/get
go vet ./functions/recipe/post
go vet ./functions/recipe/put
go vet ./functions/userview/get
go vet ./functions/userview/tags/get

go test ./functions/clipping/p_id/delete
go test ./functions/clipping/p_id/get
go test ./functions/clipping/post
go test ./functions/clipping/put
go test ./functions/clipping/search/get
go test ./functions/image/get
go test ./functions/ingredient/get
go test ./functions/ingredient/put
go test ./functions/public/image/get
go test ./functions/public/recipe/get
go test ./functions/recipe/get
go test ./functions/recipe/p_id/delete
go test ./functions/recipe/p_id/get
go test ./functions/recipe/post
go test ./functions/recipe/put
go test ./functions/userview/get
go test ./functions/userview/tags/get