AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: hello
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
  GetSentence:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: getsentence
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      VpcConfig:
        SubnetIds: "subnet-05165c1c4e56afe1b"