AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters: 
  VpcSubnetIds: 
    Type: List<AWS::EC2::Subnet::Id>
    Description: VPC Subnet IDs that Lambda will use (min 2 for HA)

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: hello
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
  GetSentence:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: getsentence
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds