AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  SecurityGroupIds: 
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group IDs that Lambda will use
  VpcSubnetIds: 
    Type: List<AWS::EC2::Subnet::Id>
    Description: VPC Subnet IDs that Lambda will use (min 2 for HA)

Resources:
  DfdApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:eu-west-2:195082537297:userpool/eu-west-2_DHttvQ5ba
  imageget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/image/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /image
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  ingredientget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/ingredient/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /ingredient
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  ingredientput:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/ingredient/
      Handler: /put
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /ingredient
            Method: put
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  publicimageget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/public/image/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /public/image
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  publicrecipeget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/public/recipe/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /public/recipe
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  recipeget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/recipe/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /recipe
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  recipepiddelete:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/recipe/p_id/
      Handler: /delete
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /recipe/{id}
            Method: delete
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  recipepidget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/recipe/p_id/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /recipe/{id}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  recipepost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/recipe/
      Handler: /post
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /recipe
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  recipeput:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/recipe/
      Handler: /put
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /recipe
            Method: put
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  userviewget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/userview/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /userview
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml

  userviewtagsget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/userview/tags/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::266057577872:role/dfd-api-lambda-role
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DfdApi
            Path: /userview/tags
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml
