AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  ConnectionString :
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: mongodb
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: hello
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
      Environment:
        Variables:
          connectionstring: !Ref ConnectionString
  GetSentence:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: getsentence
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          connectionstring: !Ref ConnectionString